function drawRectangle(rectangle,fid)

figure(fid);

line([rectangle.x1, rectangle.x1], [rectangle.y1, rectangle.y2],...
    'color','k','linestyle','--','linewidth',1);
line([rectangle.x2, rectangle.x2], [rectangle.y1, rectangle.y2],...
    'color','k','linestyle','--','linewidth',1);
line([rectangle.x1, rectangle.x2], [rectangle.y1, rectangle.y1],...
    'color','k','linestyle','--','linewidth',1);
line([rectangle.x1, rectangle.x2], [rectangle.y2, rectangle.y2],...
    'color','k','linestyle','--','linewidth',1);